spring:
  application:
    name: legalsight-speech-app
  datasource:
    url: jdbc:postgresql://localhost:5432/legal-speech
    username: legal-speech-user
    password: legal-speech-password
    driver-class-name: org.postgresql.Driver
  jpa:
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/migration/master-changeLog.yml

legal-speech:
  initial-data:
    enabled: true